//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab3_triangle {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lab3_triangle.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the first side A:.
        /// </summary>
        internal static string EnterSideA {
            get {
                return ResourceManager.GetString("EnterSideA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the second side B:.
        /// </summary>
        internal static string EnterSideB {
            get {
                return ResourceManager.GetString("EnterSideB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the third side C:.
        /// </summary>
        internal static string EnterSideC {
            get {
                return ResourceManager.GetString("EnterSideC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Equilateral triangle..
        /// </summary>
        internal static string EquilateralTriangle {
            get {
                return ResourceManager.GetString("EquilateralTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must enter either “1” or “2”.
        /// </summary>
        internal static string ErrorEnter1or2 {
            get {
                return ResourceManager.GetString("ErrorEnter1or2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your number is a complex number. Number input takes only integer numbers (remove “i” from your number). Repeat the input. You must enter your number in range of 1-10^9..
        /// </summary>
        internal static string ErrorNumberComplex {
            get {
                return ResourceManager.GetString("ErrorNumberComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your number contains invalid symbols. Remove symbols in the number. Repeat the input. You must enter your number in range of 1-10^9..
        /// </summary>
        internal static string ErrorNumberContainsInvalidSymbols {
            get {
                return ResourceManager.GetString("ErrorNumberContainsInvalidSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your number is a fractional number (remove “,” from your number). Number input takes only integer numbers. Repeat the input. You must enter your number in range of 1-10^9..
        /// </summary>
        internal static string ErrorNumberFractional {
            get {
                return ResourceManager.GetString("ErrorNumberFractional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your number is negative. Only positive numbers allowed (remove “-” from your number). Repeat the input. You must enter your number in range of 1-10^9..
        /// </summary>
        internal static string ErrorNumberNegative {
            get {
                return ResourceManager.GetString("ErrorNumberNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your number is higher than permissible value. You must enter your number in range of 1-10^9. Repeat the input..
        /// </summary>
        internal static string ErrorNumberTooBig {
            get {
                return ResourceManager.GetString("ErrorNumberTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на That is not correct side length for triangle. Sum of two sides need to be higher than third side..
        /// </summary>
        internal static string InfoBadTriangle {
            get {
                return ResourceManager.GetString("InfoBadTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Isosceles triangle..
        /// </summary>
        internal static string IsoscelesTriangle {
            get {
                return ResourceManager.GetString("IsoscelesTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose an action:
        ///You must enter ‘1’ or ‘2’.
        ///1: Compare sides. 
        ///2: Exit..
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Versatile triangle..
        /// </summary>
        internal static string VersatileTriangle {
            get {
                return ResourceManager.GetString("VersatileTriangle", resourceCulture);
            }
        }
    }
}
